
server:
  port: 8080
# cluster-name为http://127.0.0.1:9200/中的cluster_name名称
spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-application
      repositories:
        enabled: true